Fix URL errors on tests.
exchangeproject/exchange pull request #69
Opened 2018-04-20 19:30 UTC by stdevOzkar

Fix URL erros on tests.

2018-04-25 01:27 UTC, olemis requested changes
`/api/v1.0/...` => `/1.0/api/...` everywhere .

2018-04-25 01:27 UTC, olemis commented on tests/api_tests.py
> -            '/api/v1.0/addresses/{}/isvalid'.format(data),
This is wrong . It has to be `/1.0/api/...` as per Lykke specs .

2018-04-25 13:40 UTC, stdevOzkar commented
Fixed URL root for exchange_app. According to Lykke specs, we should not have the API version included.

2018-05-25 13:47 UTC, olemis requested changes

2018-05-25 13:47 UTC, olemis commented on tests/api_tests.py
> -            '/api/v1.0/addresses/{}/isvalid'.format(data),
@stdevOzkar this is the right URL prefix

2018-08-01 23:25 UTC, olemis commented
already fixed in `develop`.

2018-08-01 23:25 UTC, closed without merging